server:
  forward-headers-strategy: native

spring:
  application:
    name: api

  profiles:
    default: local

  web:
    resources:
      add-mappings: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
    api-key: ${API_KEY}
